### ISSUE TITLE
Не запускается jar файл

### ISSUE THREAD

**Issue by supremko** [supremko/sql#1]
1. Поднял MYSQL
2. Зашел в интерактивный режим
3. Проверил доступность базы app и наличие таблиц, указанных в schema.sql
4. Запустил файл командой java -jar app.jar
5. Получил ошибку
`Access denied for user 'app'@'172.30.0.1' (using password: YES)`

**Comment by ArRomanov** [comment]
* Запустить SUT (app-deadline.jar): для указания параметров подключения к БД можно использовать:
* либо переменные окружения DB_URL, DB_USER, DB_PASS
* либо указать их через флаги командной строки при запуске: -P:jdbc.url=..., -P:jdbc.user=..., -P:jdbc.password=... (внимание: при запуске флаги не нужно указывать через запятую!)
* либо можете схитрить и попробовать подобрать значения, зашитые в саму SUT

Это все описано в условии ДЗ

**Comment by supremko** [comment]
`java -jar app.jar -P:jdbc.url=jdbc:mysql://localhost:3306/app -P:jdbc.user=app -Pjdbc.password=249281008`
Также не сработала. Необходимо под рутом это делать?

**Comment by ArRomanov** [comment]
Сколько же времени мне потребовалось, чтобы заметить, что вы пропустили двоеточие в `-Pjdbc.password=249281008`

**Comment by ArRomanov** [comment]
Кроме этого, у вас volumes для постгреса и не совсем понял, для чего вы переименовали архив с приложением, но это не относится к данному вопросу

**Comment by supremko** [comment]
Слишком часто вводить полное название файла надоело, поэтому на время проверок переименовал ¯\\_(ツ)_/¯
В те 15 минут, что я искал ошибку, я тоже был уверен, что не пропустил знаков. volumes пропустил, поправил. Спасибо.

Остался один вопрос по правильному использованию sql файла. Я могу, конечно же, выполнить его вручную в консоли mysql, просто набрав команду из файла, но хотел бы понять как это должно работать по логике задания. Нашел способ `docker-compose exec mysql mysql -u app -p app < schema.sql`, но он отображает ошибку
`the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'`
Если вставлять winpty в начале команды, как говорят на форумах, то получаю еще одну ошибку
```
winpty docker-compose exec mysql mysql -u app -p app < schema.sql
"winpty" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

```

**Comment by ArRomanov** [comment]
Все намного проще, чем вы думаете. На оф. странице образа mysql есть информация о том, как инициализировать базу данных при первом запуске, там все достаточно понятно и просто.

**Comment by supremko** [comment]
_Windows - сделай любое легкое решение сложным._
1. создал папку docker-entrypoint-initdb.d
2. перенес sql файл в эту папку
3. пересоздал контейнер с --force-recreate
4. проверил app - пусто
5. нашел информацию, что на это может влиять volume
6. закомментировал volume
7. пересоздал контейнер с --force-recreate
8. проверил app - пусто

На форумах в старых решениях предлагают странные перемещения, например `RUN mkdir -p /docker-entrypoint-initdb.d && mv myScript.sql /docker-entrypoint-initdb.d/myScript.sql`, но файл же итак там.

**Comment by ArRomanov** [comment]
Не совсем понял, сделали ли вы так или по-другому.
Нужно прописать дополнительный volumes `./db_init:/docker-entrypoint-initdb.d`, в директорию db_init положить файл со схемой. Когда вольюмс пропишется, то контейнер увидит файл и запустит его. Следите в логах за процессом docker-compose logs -f

**Comment by ArRomanov** [comment]
Директория на вашей машине, конечно, может называться по другому

**Comment by supremko** [comment]
Разве мы не приходим в таком случае к той же ситуации, что и была с postgres - папку в системе докер не видит или не воспринимает и надо указывать локальную?
Попробовал так сделать и также ничего не изменилось. В логах ошибок не вижу
```
docker-compose logs -f
Attaching to sql_mysql_1
mysql_1  | 2019-12-28 09:57:57+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.18-1debian9 started.
mysql_1  | 2019-12-28 09:57:57+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1  | 2019-12-28 09:57:57+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.18-1debian9 started.
mysql_1  | 2019-12-28T09:57:58.178558Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is
the default. Consider not using this option as it' is deprecated and will be removed in a future release.
mysql_1  | 2019-12-28T09:57:58.178686Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.18) starting as process 1
mysql_1  | 2019-12-28T09:57:58.923142Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_1  | 2019-12-28T09:57:58.931385Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the
path is accessible to all OS users. Consider choosing a different directory.
mysql_1  | 2019-12-28T09:57:58.953447Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.18'  socket: '/var/
run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
mysql_1  | 2019-12-28T09:57:59.040022Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind
-address: '::' port: 33060
```
Но таблиц в app также нет.

**Comment by ArRomanov** [comment]
А напомните, какая у вас ОС? У меня win10 home. Вот шаги, которые я выполнил:
1. Под тем же пользователем, под которым устанавливал docker-toolbox, на рабочем столе кликнул ПКМ, вызвал `Git Bash Here`, в открывшемся терминале выполнил `git clone https://github.com/supremko/sql.git`
2. Перешел в склонированную директорию и ничего не изменяя выполнил docker-compose up -d
3. Потом просто запустил логи `docker-compose logs -f mysql` и дождался инициализации
<details><summary>Результат в логах</summary>
mysql_1  | 2019-12-28 17:38:10+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.18-1debian9 started.
mysql_1  | 2019-12-28 17:38:11+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1  | 2019-12-28 17:38:11+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.18-1debian9 started.
mysql_1  | 2019-12-28 17:38:12+00:00 [Note] [Entrypoint]: Initializing database files
mysql_1  | 2019-12-28T17:38:12.075966Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this opti
on as it' is deprecated and will be removed in a future release.
mysql_1  | 2019-12-28T17:38:12.077697Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.18) initializing of server in progress as process 44
mysql_1  | 2019-12-28T17:38:24.970437Z 5 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.

mysql_1  | 2019-12-28 17:38:39+00:00 [Note] [Entrypoint]: Database files initialized
mysql_1  | 2019-12-28 17:38:39+00:00 [Note] [Entrypoint]: Starting temporary server
mysql_1  | 2019-12-28T17:38:44.207201Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this opti
on as it' is deprecated and will be removed in a future release.
mysql_1  | 2019-12-28T17:38:44.207665Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.18) starting as process 93
mysql_1  | 2019-12-28T17:38:46.765009Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_1  | 2019-12-28T17:38:46.775674Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consi
der choosing a different directory.
mysql_1  | 2019-12-28T17:38:46.881140Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.18'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL C
ommunity Server - GPL.
mysql_1  | 2019-12-28T17:38:46.941069Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock'
mysql_1  | 2019-12-28 17:38:46+00:00 [Note] [Entrypoint]: Temporary server started.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql_1  | 2019-12-28 17:39:29+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: ooCai7oosooR8chie6oox3aiyaiyaihu
mysql_1  | 2019-12-28 17:39:29+00:00 [Note] [Entrypoint]: Creating database app
mysql_1  | 2019-12-28 17:39:29+00:00 [Note] [Entrypoint]: Creating user app
mysql_1  | 2019-12-28 17:39:29+00:00 [Note] [Entrypoint]: Giving user app access to schema app
mysql_1  |
**mysql_1  | 2019-12-28 17:39:29+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/schema.sql**
mysql_1  |
mysql_1  |
mysql_1  | 2019-12-28 17:39:30+00:00 [Note] [Entrypoint]: Stopping temporary server
mysql_1  | 2019-12-28T17:39:30.171266Z 15 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.18).
mysql_1  | 2019-12-28T17:39:32.218608Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.18)  MySQL Community Server - GPL.
mysql_1  | 2019-12-28 17:39:33+00:00 [Note] [Entrypoint]: Temporary server stopped
mysql_1  |
mysql_1  | 2019-12-28 17:39:33+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
mysql_1  |
mysql_1  | 2019-12-28T17:39:33.829118Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this opti
on as it' is deprecated and will be removed in a future release.
mysql_1  | 2019-12-28T17:39:33.829503Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.18) starting as process 1
mysql_1  | 2019-12-28T17:39:35.285209Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_1  | 2019-12-28T17:39:35.295376Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consi
der choosing a different directory.
mysql_1  | 2019-12-28T17:39:35.397460Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.18'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQ
L Community Server - GPL.
mysql_1  | 2019-12-28T17:39:35.498603Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
</details>

Выходит, что все работает корректно. Попробуйте остановить, а затем удалить все контейнеры и повторить все шаги, начиная с клонирования директории.
* docker ps - покажет все запущенные контейнеры
* docker ps -a - покажет все когда-либо созданные контейнеры
* docker ps -aq - покажет только id всех контейнеров
* docker container rm <container_id> - удаляет контейнер по id

Если не сможете найти решение, то пишите в slack и будем пытаться в интерактивном режиме, возможно организуем подключение через teamviewer.

**Comment by supremko** [comment]
В том то и проблема, что у меня Win10 Pro с Docker Desktop и на нем текущие настройки не запускают файл
вот перезапустил контейнер без -d
```
docker-compose up --force-recreate
Creating network "sql_default" with the default driver
Creating sql_mysql_1 ... done
Attaching to sql_mysql_1
mysql_1  | 2019-12-28 19:02:14+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.18-1debian9 started.
mysql_1  | 2019-12-28 19:02:14+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1  | 2019-12-28 19:02:14+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.18-1debian9 started.
mysql_1  | 2019-12-28T19:02:15.118053Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is
the default. Consider not using this option as it' is deprecated and will be removed in a future release.
mysql_1  | 2019-12-28T19:02:15.118156Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.18) starting as process 1
mysql_1  | 2019-12-28T19:02:15.657066Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_1  | 2019-12-28T19:02:15.665749Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the
path is accessible to all OS users. Consider choosing a different directory.
mysql_1  | 2019-12-28T19:02:15.688656Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.18'  socket: '/var/
run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
mysql_1  | 2019-12-28T19:02:15.831759Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind
-address: '::' port: 33060

```

**Comment by ArRomanov** [comment]
На данный момент есть еще одна идея, вам стоит в volumes перед data поставить символы "./", чтобы директория data создавалась в текущем каталоге. Сейчас, она создана по абсолютному пути и она не пересоздается каждый раз. Вы запускаете docker-compose и база данных сразу видит готовые файлы для использования, поэтому, возможно, не запускает инициализацию.

**Comment by supremko** [comment]
Неожиданный результат. То, что не умел делать postgres в предыдущем задании - запись не в локальную папку data, а виндовую, mysql спокойно сделал и в итоге создал таблицы.
